#!/bin/bash
echo '1.打印参数个数 $#: '$#
echo '2.打印脚本所有传入参数 $* : '"$*"
echo '3.打印脚本所有传入参数 $@ : '$@
echo '4.打印脚本运行当前进程ID $$: '"$$"
echo '5.打印后台运行最后一个进程ID $!: '$!
echo '6.打印脚本执行的方式(set命令) $-: '$-
echo '7.打印最后命令的退出状态 $?: '$?
echo '8.$@, $* 被“”括起来时的区别(没别括起来无区别)'
echo '   对"$@"进行for'
for i in "$@"; do
 echo -e "\t"$i
done

echo '   对"$*"进行for'
for i in "$*"; do
	echo -e '\t'$i
done
